- name: HAProxy
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
    
  vars_prompt:
    - name: 'haproxy_selection'
      prompt: "Choose the HAProxy distribution: \n
      1: HAProxy 1.7\n(ont support ubuntu20.04)
      2: HAProxy 1.8\n(ont support ubuntu20.04)
      3: HAProxy 2.0\n
      4: HAProxy 2.1\n
      5: HAProxy 2.2\n
      6: HAProxy 2.3(only support ubuntu20.04 and centos7)\n
      7: HAProxy 2.4\n
      8: HAProxy 2.5\n"
      private: no
      default: 1

  vars:
    haproxy_select:
      '1': "1.7"
      '2': "1.8"      
      '3': "2.0"
      '4': "2.1"
      '5': "2.2"
      '6': "2.3"
      '7': "2.4"
      '8': "2.5"
      
    haproxy_version: "{{haproxy_select[haproxy_selection]}}"

  roles:
    - { role: role_common, tags: "role_common"}  
    - { role: role_cloud, tags: "role_cloud" }
    - { role: role_haproxy, tags: "role_haproxy"}
    - { role: role_init, tags: "role_init"}
    - { role: role_preend, tags: "preend" }
    - { role: role_end, tags: "role_end" }
